### ISSUE TITLE
Acessability 

### ISSUE THREAD

**Issue by mai-space** [mai-space/minimal-stylesheet-maximum-impact#6]
```scss
// Variables and Mixins
$primary-color: #333;
$secondary-color: #666;
$font-stack: 'Helvetica Neue', Arial, sans-serif;

@mixin accessible-focus($focus-color: $primary-color) {
  &:focus {
    outline: 2px dashed $focus-color;
    outline-offset: 2px;
  }
}

// Base Styles
body {
  font-family: $font-stack;
  color: $primary-color;
  line-height: 1.6;
}

// Accessibility Improvements
a {
  @include accessible-focus;
  color: $secondary-color;
  text-decoration: none;
  
  &:hover,
  &:active {
    text-decoration: underline;
  }
}

// Layout Components
.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 15px;
}

// Reusable Components
.button {
  padding: 0.6em 1.2em;
  border: none;
  background-color: $primary-color;
  color: white;
  font-family: $font-stack;
  font-size: 1rem;
  cursor: pointer;
  
  &:hover {
    background-color: darken($primary-color, 10%);
  }
  
  &[disabled] {
    opacity: 0.5;
    cursor: not-allowed;
  }
}

// Media Queries for Responsiveness
@media screen and (max-width: 768px) {
  .container {
    padding: 0 10px;
  }
  
  .button {
    padding: 0.5em 1em;
  }
}
```

This SCSS structure uses variables for easy theme management, a mixin for accessible focus states, base styles for body text, accessibility-friendly link styles, a container for layout management, reusable button components, and media queries for responsiveness.
